### PR TITLE
Fallback is to assume we are running on AWS

### PR DESCRIPTION
**Pull request by VaughanJ**
When no credentials are supplied, assume we are running on AWS and therefore already have credentials to push to S3. No AWSCredentials object needed.

Presendce
Access Key and Secret Key
Role from Instance Profile
Credentials of the instance/task running on AWS.

### CODE REVIEW

**Comment by mieliespoor** [comment]
we couldn't test this on our side before we submitted the PR, so would appreciate if this could be tested by Proget. 

We tested the creation of the s3 client separately and that returned the desired results, so the theory is that this should work.

Ideally, this should be easily tested with unit tests, but because this doesn't use dependency injection, or similar, unit testing becomes near impossible. I would be great if changes could be made by Proget that would allow unit testing as for a library like this, unit tests should be a core and base requirement.

**Comment by mieliespoor** [comment]
@gdivis would you mind to review this again?

**Comment by gdivis** [comment]
We've reviewed this and I've just merged it in. It's available now as a a prerelease extension in v2.0.3-ci.1. We'll do some regression testing before we deploy it as stable. Thanks!

**Comment by mieliespoor** [comment]
Nice one! Thanks!

**Pull request merged**
