### PR TITLE
fix: iam role regex

### PR DESCRIPTION
**Pull request by mieliespoor**
This will fix the regex to check for a valid IAM role. Introduced in #22 for #21 

Currently a valid IAM Role arn, arn:aws:iam::123456789012:role/security-container-proget-role return the error of an invalid IAM Role which is unexpected.

### CODE REVIEW

**Comment by cvmcalister** [comment]
Next stop: Fargate 👍

**Comment by gdivis** [comment]
@mieliespoor Thanks! We'll get an updated extension out with this fix in a day or two.

**Comment by mieliespoor** [comment]
@gdivis any idea when this will be released?

**Comment by gdivis** [comment]
@mieliespoor Sorry about that. This was supposed to be released a while ago, but didn't get deployed. It's released now!

**Pull request merged**
